# Generated by Django 3.1.7 on 2021-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='category'),
            preserve_default=False,
        ),
    ]
